
version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p-tracker
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: tracker-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: p_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db-data: